"""Version local assets so workers and WASM cannot mix builds from browser cache."""
from pathlib import Path
import hashlib,re
ROOT=Path(__file__).resolve().parents[1]
def version_assets():
 web=ROOT/'web';files=sorted([p for p in web.iterdir() if p.suffix in ('.js','.css','.wasm') and p.name!='asset-version.js'])
 version=hashlib.sha256(b''.join(p.name.encode()+p.read_bytes() for p in files)).hexdigest()[:16]
 (web/'asset-version.js').write_text('/* Generated by the build. */\nglobalThis.MMSAssetVersion="'+version+'";\n')
 p=web/'index.html';text=p.read_text(encoding='utf-8');text=re.sub(r'((?:src|href)="[a-z0-9-]+\.(?:js|css))(?:\?v=[^"]*)?("[ >])',r'\1?v='+version+r'\2',text);p.write_text(text,encoding='utf-8');return version
if __name__=='__main__':print(version_assets())
