/* Shared TX picture editor. GPL-3.0-or-later. */
'use strict';
function imageEditor(){
 if(!tx.source||tx.busy)return;
 const settings={rotation:0,mirror:false,flip:false,brightness:100,contrast:100,saturation:100,left:0,top:0,right:0,bottom:0};
 dialog('Edit TX picture',`<div class="dialog-body"><canvas id="edit-preview" class="template-preview"></canvas><div class="form-row"><label for="edit-rotation">Rotate</label><select id="edit-rotation"><option value="0">0°</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></div><label><input id="edit-mirror" type="checkbox">Mirror horizontally</label> <label><input id="edit-flip" type="checkbox">Flip vertically</label>${['brightness','contrast','saturation'].map(key=>`<div class="form-row"><label for="edit-${key}">${key[0].toUpperCase()+key.slice(1)} (%)</label><input id="edit-${key}" type="range" min="0" max="200" value="100"></div>`).join('')}<fieldset><legend>Crop margins (%)</legend>${['left','top','right','bottom'].map(key=>`<div class="form-row"><label for="edit-${key}">${key[0].toUpperCase()+key.slice(1)}</label><input id="edit-${key}" type="number" min="0" max="45" value="0"></div>`).join('')}</fieldset></div>`,'<button id="edit-apply">Apply</button><button data-dialog="close">Cancel</button>');
 const render=(canvas,preview)=>{const source=tx.source,x=source.width*settings.left/100,y=source.height*settings.top/100,w=source.width*(100-settings.left-settings.right)/100,h=source.height*(100-settings.top-settings.bottom)/100,rotate=settings.rotation%180!==0,scale=preview?Math.min(1,640/Math.max(w,h)):1;canvas.width=Math.max(1,Math.round((rotate?h:w)*scale));canvas.height=Math.max(1,Math.round((rotate?w:h)*scale));const ctx=canvas.getContext('2d');ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(settings.rotation*Math.PI/180);ctx.scale(settings.mirror?-1:1,settings.flip?-1:1);ctx.drawImage(source,x,y,w,h,-w*scale/2,-h*scale/2,w*scale,h*scale);ctx.restore();const data=ctx.getImageData(0,0,canvas.width,canvas.height),b=settings.brightness/100,c=settings.contrast/100,s=settings.saturation/100;for(let i=0;i<data.data.length;i+=4){const d=data.data,l=d[i]*.299+d[i+1]*.587+d[i+2]*.114;for(let channel=0;channel<3;channel++)d[i+channel]=((l+(d[i+channel]-l)*s)*b-128)*c+128;}ctx.putImageData(data,0,0);};
 document.querySelectorAll('#dialog-content input,#dialog-content select').forEach(element=>element.oninput=()=>{const key=element.id.replace('edit-','');settings[key]=element.type==='checkbox'?element.checked:Math.max(0,Math.min(['left','top','right','bottom'].includes(key)?45:key==='rotation'?270:200,Number(element.value)||0));render($('edit-preview'),true);});render($('edit-preview'),true);
 $('edit-apply').onclick=async()=>{try{const canvas=document.createElement('canvas');render(canvas,false);await setTxImage(canvas,tx.name);$('modal').close();}catch(error){failure(error);}};
}
actions['image-editor']=imageEditor;
const txEdit=document.createElement('button');txEdit.className='icon needs-tx-image';txEdit.dataset.action='image-editor';txEdit.title='Edit TX picture';txEdit.innerHTML='<img src="assets/SBAdj.png" alt="Edit TX picture">';$('tx-toolbar').append(txEdit);
