/* File-oriented features shared by both layouts. No device control or packages. */
'use strict';
function digitalFields(prefix,settings=digital.settings){return [['mode','Mode',['A','B','E']],['qam','QAM',['4','16','64']],['protection','Protection',['High','Normal']],['bandwidth','Bandwidth',['2.2 kHz','2.5 kHz']],['interleave','Interleave',['Long','Short']],['rs','Reed–Solomon',['None','RS1 (224)','RS2 (192)','RS3 (160)','RS4 (128)']]].map(([key,label,values])=>`<div class="form-row"><label for="${prefix+key}">${label}</label><select id="${prefix+key}">${values.map((value,i)=>`<option value="${i}" ${settings[key]===i?'selected':''}>${value}</option>`).join('')}</select></div>`).join('');}
function digitalGenerateDialog(fix=null,original=null){
  if(tx.busy)return;
  if(!original&&!digital.source&&!tx.source){dialog('Generate DRM audio','<div class="dialog-body"><p>Open a TX picture or a digital file first.</p></div>','<button id="drm-choose">Open file…</button><button data-dialog="close">Cancel</button>');$('drm-choose').onclick=()=>$('digital-file').click();return;}
  dialog('Generate DRM audio',`<div class="dialog-body"><p>${escapeHtml(original?.name||digital.source?.name||tx.name||'TX image')} ${fix?'· '+fix.length+' requested segments':''}</p>${digitalFields('drm-')}<div class="form-row"><label>Image format</label><select id="drm-format"><option value="jp2">JPEG 2000</option><option value="png">PNG (lossless)</option><option value="jpeg">JPEG</option></select></div><div class="form-row"><label>JPEG 2000 ratio</label><input id="drm-ratio" type="number" min="1" max="1000" value="20"></div><label><input id="drm-vox" type="checkbox" ${state.settings.txVox?'checked':''}>VOX lead-in tone</label><label><input id="drm-cw" type="checkbox" ${state.settings.txCw?'checked':''}>Append CW ID</label><div class="form-row"><label for="drm-call">My callsign</label><input id="drm-call" maxlength="9" value="${escapeHtml(state.settings.myCall)}"></div><p>Generate QSSTV-compatible HAMDRM as a 48000 Hz, 16-bit mono WAV.</p>${!original&&digital.source&&tx.source?'<label><input id="drm-use-image" type="checkbox">Use current TX image instead of the binary file</label>':''}</div>`,'<button id="drm-generate">Generate</button><button data-dialog="close">Cancel</button>');
  $('drm-format').value=state.settings.digitalImageFormat||'jp2';$('drm-ratio').value=state.settings.digitalImageRatio||20;
  const refreshRS=()=>{const image=!original&&(!digital.source||$('drm-use-image')?.checked);$('drm-format').disabled=!image;$('drm-ratio').disabled=!image;const bsr=(original||digital.source)?.name==='bsr.bin'&&!$('drm-use-image')?.checked;$('drm-rs').disabled=bsr;$('drm-rs').value=bsr?0:digital.settings.rs;};refreshRS();if($('drm-use-image'))$('drm-use-image').onchange=refreshRS;
  $('drm-generate').onclick=async()=>{try{for(const key of ['mode','qam','protection','bandwidth','interleave','rs'])if(key!=='rs'||!$('drm-rs').disabled)digital.settings[key]=Number($('drm-'+key).value);state.settings.txVox=$('drm-vox').checked;state.settings.txCw=$('drm-cw').checked;state.settings.myCall=$('drm-call').value.trim().toUpperCase();if(!/^[A-Z0-9 /-]{0,9}$/.test(state.settings.myCall))throw Error('Use up to nine callsign characters.');persist('digital',digital.settings);persist('settings',state.settings);let source=original||digital.source;if(!source||$('drm-use-image')?.checked){const format=$('drm-format').value,ratio=Math.max(1,Math.min(1000,Number($('drm-ratio').value)||20));state.settings.digitalImageFormat=format;state.settings.digitalImageRatio=ratio;persist('settings',state.settings);source={name:(tx.name||'image').replace(/\.[^.]*$/,'')+'.'+(format==='jpeg'?'jpg':format),bytes:await encodeDigitalPicture($('tx-picture'),format,ratio)};}await generateDigital({...source,transport:original?Number(original.transport)||0:Math.floor(Math.random()*65533)+3},fix);}catch(error){failure(error);}};
}
async function generateDigital(source,fix){
  if(!digital.encoder)digital.encoder=await QSSTVDigitalEngine.create();
  const token=++tx.token;tx.busy=true;updateImageButtons();notifyView();
  dialog('Generate DRM audio',`<div class="dialog-body"><p>${escapeHtml(source.name)}</p><progress id="drm-progress" max="1" value="0" style="width:100%"></progress><p id="drm-progress-label">Preparing digital encoder…</p></div>`,'<button data-dialog="close">Cancel</button>');
  const cancel=()=>{if(tx.token===token)++tx.token;};$('modal').addEventListener('close',cancel);
  try{
    await digital.encoder.call('start',{...digital.settings,name:source.name,bytes:source.bytes,transport:source.transport||0,call:state.settings.myCall,fix:fix||[]});
    const chunks=[];let bytes=0,block;
    do{if(token!==tx.token)return;block=await digital.encoder.call('read');if(token!==tx.token)return;chunks.push(block.pcm);bytes+=block.pcm.length;if(bytes>512*1024*1024)throw Error('Generated audio exceeds the 512 MB limit.');$('drm-progress').value=block.progress;$('drm-progress-label').textContent=`Generating DRM audio… ${duration(bytes/96000)}`;await new Promise(resolve=>setTimeout(resolve,0));}while(!block.done);
    if(source.name!=='bsr.bin')digital.lastTransmission={...source,settings:{...digital.settings}};tx.wave=await finishGeneratedAudio(chunks,48000);bytes=tx.wave.size-44;tx.waveName=source.name.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_')+'.drm.wav';if(tx.waveUrl)URL.revokeObjectURL(tx.waveUrl);tx.waveUrl=URL.createObjectURL(tx.wave);$('modal').removeEventListener('close',cancel);
    dialog('Save DRM audio',`<div class="dialog-body"><p>${escapeHtml(source.name)} · ${duration(bytes/96000)} · ${(bytes/1024/1024).toFixed(2)} MB</p><p>48000 Hz · 16-bit mono</p></div>`,'<a class="dialog-button" id="drm-download">Save WAV</a><button id="drm-decode">Decode WAV</button><button data-dialog="close">Close</button>');$('drm-download').href=tx.waveUrl;$('drm-download').download=tx.waveName;$('drm-decode').onclick=()=>{$('modal').close();setProtocol('drm');selectTab('rx');if(window.QSSTVUI&&state.settings.interface==='qsstv')qTab('receive');loadAudio(new File([tx.wave],tx.waveName,{type:'audio/wav'})).catch(failure);};status('DRM audio generated.');
  }finally{$('modal').removeEventListener('close',cancel);tx.busy=false;updateImageButtons();notifyView();await digital.encoder?.call('cancel').catch(()=>{});if(token!==tx.token)status('Digital audio generation canceled.');}
}
function digitalFilesDialog(){
  dialog('Received digital files',`<div class="dialog-body"><div class="dialog-scroll digital-file-list"><table><thead><tr><th>File</th><th>Bytes</th><th>Call</th><th></th></tr></thead><tbody>${digital.files.map((file,i)=>`<tr><td>${escapeHtml(file.name)}</td><td>${file.bytes.length}</td><td>${escapeHtml(file.call)}</td><td><button data-file-save="${i}">Save…</button>${file.name==='bsr.bin'?` <button data-file-fix="${i}">FIX…</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4">No digital files received.</td></tr>'}</tbody></table></div><p>Received pictures, including JPEG 2000, also appear in the shared image history.</p></div>`);
  document.querySelectorAll('[data-file-save]').forEach(button=>button.onclick=()=>{const file=digital.files[Number(button.dataset.fileSave)];download(file.blob,file.name.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_'));});
  document.querySelectorAll('[data-file-fix]').forEach(button=>button.onclick=()=>{try{fixDialog(new TextDecoder().decode(digital.files[Number(button.dataset.fileFix)].bytes));}catch(error){failure(error);}});
}
async function bsrDialog(){
  const result=await digital.engine?.call('bsr');if(!result?.text){dialog('Block status request','<div class="dialog-body"><p>No incomplete digital transfer is available.</p></div>');return;}
  dialog('Block status request',`<div class="dialog-body"><p>Request missing segments from the current DRM transfer.</p><textarea readonly rows="9" style="width:100%">${escapeHtml(result.text)}</textarea></div>`,'<button id="bsr-save">Save bsr.bin</button><button id="bsr-wav">Generate BSR WAV…</button><button data-dialog="close">Close</button>');
  const bytes=new TextEncoder().encode(result.text);$('bsr-save').onclick=()=>download(new Blob([bytes]),'bsr.bin');$('bsr-wav').onclick=()=>{digital.source={name:'bsr.bin',bytes};digitalGenerateDialog();};
}
function parseBSR(text){
  if(typeof text!=='string'||text.length>65536)throw Error('BSR file is too large.');
  const lines=text.trim().split(/\r?\n/),transport=Number(lines[0]),size=Number(lines[2]),end=lines.indexOf('-99');
  if(lines[1]!=='H_OK'||!Number.isInteger(transport)||transport<3||transport>65535||!Number.isInteger(size)||size<1||size>8191||end<4)throw Error('Invalid QSSTV BSR header.');
  const missing=[];let previous=-1;
  for(let i=3;i<end;i++){
    const number=Number(lines[i]);
    if(number===-1){const next=Number(lines[++i]);if(previous<0||i>=end||!Number.isInteger(next)||next>=8192||next<=previous)throw Error('Invalid BSR range.');for(let n=previous+1;n<=next;n++)missing.push(n);previous=next;}
    else{if(!lines[i].trim()||!Number.isInteger(number)||number<0||number>=8192)throw Error('Invalid BSR segment.');missing.push(number);previous=number;}
    if(missing.length>8192)throw Error('Too many BSR segments.');
  }
  const name=lines[end+1]||'',code=lines[end+2]||'',rs=/\.rs([1-4])$/i.exec(name);
  const settings=/^[0-2][01][01][0-2][01]$/.test(code)?{mode:Number(code[0]),bandwidth:Number(code[1]),protection:Number(code[2]),qam:Number(code[3]),interleave:Number(code[4]),rs:rs?Number(rs[1]):0}:null;
  return {transport,name,settings,missing:[...new Set(missing)]};
}
function fixDialog(request=null){
  dialog('FIX / retransmit',`<div class="dialog-body"><p>The last generated digital file is retained for exact retransmission. Otherwise load the original file and use the same modem and RS settings. Enter missing segment numbers or import a QSSTV BSR file.</p><textarea id="fix-segments" rows="6" style="width:100%" placeholder="0, 3, 4, 5"></textarea><p id="fix-name"></p>${digital.source&&digital.source.name!=='bsr.bin'?`<label><input id="fix-current" type="checkbox" ${!digital.lastTransmission?'checked':''}>Use loaded file: ${escapeHtml(digital.source.name)}</label>`:''}<label>Transport ID (0 = legacy ID) <input id="fix-transport" type="number" min="0" max="65535" value="${digital.lastTransmission?.transport||0}"></label></div>`,'<button id="fix-load">Load BSR…</button><button id="fix-generate">Generate FIX WAV…</button><button data-dialog="close">Cancel</button>');
  let requestedSettings=null;
  const fill=text=>{const data=parseBSR(text);requestedSettings=data.settings;$('fix-segments').value=data.missing.join(', ');$('fix-name').textContent=data.name;$('fix-transport').value=data.transport;};
  if(request)fill(request);
  $('fix-load').onclick=()=>$('bsr-file').click();$('bsr-file').onchange=async()=>{try{const file=$('bsr-file').files[0];if(!file)return;if(file.size>65536)throw Error('BSR file is too large.');fill(await file.text());}catch(error){failure(error);}finally{$('bsr-file').value='';}};
  $('fix-generate').onclick=()=>{const numbers=$('fix-segments').value.split(/[\s,]+/).filter(Boolean).map(Number);if(!numbers.length||numbers.some(n=>!Number.isInteger(n)||n<0||n>=8192)){failure(Error('Enter segment numbers from 0 to 8191.'));return;}const original=$('fix-current')?.checked?digital.source:digital.lastTransmission||digital.source;if(!original||original.name==='bsr.bin'){failure(Error('Load the original digital file first.'));return;}const transport=Number($('fix-transport').value);if(!Number.isInteger(transport)||transport<0||transport>65535||(transport>0&&transport<3)){failure(Error('Use a transport ID from 3 to 65535, or 0 for the legacy filename ID.'));return;}if(original.settings||requestedSettings)Object.assign(digital.settings,original.settings||requestedSettings);digitalGenerateDialog([...new Set(numbers)],{...original,transport:Number($('fix-transport').value)||original.transport});};
}
function qConfiguration(initial='Gui'){
  const s=state.settings,tabs=['Operator','Directories','Gui','Sound','CAT','CW','Repeater','FTP','Waterfall','Hybrid','DRM Profiles'];
  dialog('Configuration',`<div class="config-layout"><div class="tabs config-tabs">${tabs.map(name=>`<button data-config="${name}" ${['CAT','FTP','Hybrid'].includes(name)?'disabled':''}>${name}</button>`).join('')}</div><div class="config-pane" id="config-pane"></div></div>`,'<button id="config-ok">OK</button><button data-dialog="close">Cancel</button>');
  const staged={...s},stagedDigital={...digital.settings};
  const check=(key,label)=>`<label><input data-config-key="${key}" type="checkbox" ${staged[key]?'checked':''}>${label}</label>`,input=(key,label,type='text',attrs='')=>`<label>${label}<input data-config-key="${key}" type="${type}" value="${escapeHtml(staged[key])}" ${attrs}></label>`;
  function render(name){document.querySelectorAll('[data-config]').forEach(b=>b.classList.toggle('selected',b.dataset.config===name));const html={
    Operator:`<fieldset><legend>Operator</legend>${input('myCall','Callsign')}${input('operatorName','Name')}${input('operatorQth','QTH')}${input('operatorLocator','Locator')}</fieldset>`,
    Directories:'<fieldset><legend>Browser storage</legend><p>Image history and stock pictures are kept in IndexedDB on this site. Settings, profiles, templates and logs use localStorage.</p><p>Use File → Export history and Export log for backups. Generated audio and received digital files are saved with browser downloads.</p></fieldset><button data-action="export-history">Export history…</button> <button data-action="import-history">Import history…</button>',
    Gui:`<div class="config-grid"><section><b>Images</b>${check('stretch','Stretch')}${input('backgroundColor','Background Color','color')}${input('imageBackground','Image Background color','color')}<b>Performance</b>${check('slowCpu','Low CPU mode')}${check('confirmDelete','Ask before deleting images')}${check('confirmClose','Ask before closing')}</section><section><b>Gallery</b>${input('galleryRows','Rows','number','min="1" max="8"')}${input('galleryColumns','Columns','number','min="1" max="8"')}<b>Resolution</b>${check('lowResolution','Low screen resolution')}</section></div>`,
    Sound:`<fieldset><legend>Sound Input</legend><p>Browser microphone / line input or uploaded audio file.</p><label>Channel<select data-config-key="channel"><option value="left">Left / mono</option><option value="right">Right</option><option value="mix">Average</option></select></label>${check('recordAudio','Record microphone input to WAV')}${input('recordLimit','Maximum recording size (MB)','number','min="1" max="256"')}<button data-action="microphone">Select microphone…</button></fieldset><fieldset><legend>Sound Output</legend><p>Generate WAV files. SSTV: 11025 Hz. DRM: 48000 Hz. Hardware and PTT output are disabled.</p><label><input type="checkbox" disabled>PTT tone on other channel</label></fieldset>`,
    CW:`<fieldset><legend>CW identification</legend>${input('cwWpm','Words per minute','number','min="5" max="60"')}${input('cwFrequency','Tone frequency (Hz)','number','min="400" max="2000"')}<button data-action="cw-id">Generate CW ID WAV…</button></fieldset>`,
    Repeater:'<fieldset><legend>Offline replay</legend><p>Copy a received picture to TX and generate a new SSTV or DRM audio file. Automatic on-air retransmission is disabled.</p><button data-action="copy-to-tx">Copy received picture to TX</button></fieldset>',
    Waterfall:`<fieldset><legend>Waterfall</legend>${input('waterfallMax','Maximum dB','number','min="-80" max="0"')}${input('waterfallRange','Range dB','number','min="10" max="80"')}${input('waterfallAverage','Average','number','min="0" max="0.99" step="0.01"')}</fieldset>`,
    'DRM Profiles':`<fieldset><legend>Current DRM profile</legend>${digitalFields('config-drm-',stagedDigital)}</fieldset><p>These settings are shared between MMSSTV and QSSTV. Receive mode is detected automatically.</p>`
  };$('config-pane').innerHTML=html[name]||'';document.querySelectorAll('[data-config-key]').forEach(element=>{const key=element.dataset.configKey;if(element.tagName==='SELECT')element.value=staged[key];element.onchange=()=>{staged[key]=element.type==='checkbox'?element.checked:element.type==='number'?Number(element.value):element.value;};});}
  document.querySelectorAll('[data-config]').forEach(button=>button.onclick=()=>{if($('config-drm-mode'))for(const key of ['mode','qam','protection','bandwidth','interleave','rs'])stagedDigital[key]=Number($('config-drm-'+key).value);render(button.dataset.config);});
  $('config-ok').onclick=()=>{if($('config-drm-mode'))for(const key of ['mode','qam','protection','bandwidth','interleave','rs'])stagedDigital[key]=Number($('config-drm-'+key).value);digital.settings=stagedDigital;state.settings=staged;state.settings.galleryRows=Math.max(1,Math.min(8,Number(staged.galleryRows)||4));state.settings.galleryColumns=Math.max(1,Math.min(8,Number(staged.galleryColumns)||4));persist('settings',state.settings);persist('digital',digital.settings);state.settings.savePercent=Math.max(0,Math.min(100,Number(staged.savePercent)||0));state.settings.waterfallMax=Math.max(-80,Math.min(0,Number(staged.waterfallMax)||-25));state.settings.waterfallRange=Math.max(10,Math.min(80,Number(staged.waterfallRange)||35));state.settings.waterfallAverage=Math.max(0,Math.min(.99,Number(staged.waterfallAverage)||0));persist('settings',state.settings);document.body.style.backgroundColor=staged.backgroundColor;for(const [id,key]of [['q-max-db','waterfallMax'],['q-range','waterfallRange'],['q-average','waterfallAverage']])if($(id))$(id).value=staged[key];qsstv.classList.toggle('q-low-resolution',!!staged.lowResolution);applySettings().catch(failure);$('modal').close();notifyView();};render(initial);
}
let templateSettings={text:'CQ CQ CQ\nde %CALL%',color:'#00ffff',background:'#000000',backgroundAlpha:0,fontSize:28,x:10,y:35,outline:true,...saved('template',{})};
function expandedTemplate(text){return text.replace(/%(CALL|TO|OP|RSV|X|Y|Z|DATE|TIME|QTH|LOCATOR)%/g,(_,key)=>({CALL:state.settings.myCall,TO:$('q-to')?.value||$('call').value,OP:$('q-op')?.value||state.settings.operatorName,RSV:$('q-rsv')?.value||$('his-rst').value,X:$('q-x')?.value,Y:$('q-y')?.value,Z:$('q-z')?.value,DATE:new Date().toISOString().slice(0,10),TIME:new Date().toISOString().slice(11,16),QTH:state.settings.operatorQth,LOCATOR:state.settings.operatorLocator}[key]||''));}
function applyTemplate(canvas,settings=templateSettings){const ctx=canvas.getContext('2d');ctx.save();ctx.globalAlpha=Number(settings.backgroundAlpha)||0;ctx.fillStyle=settings.background;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalAlpha=1;ctx.font=`bold ${settings.fontSize}px Arial`;ctx.lineWidth=Math.max(1,settings.fontSize/12);ctx.strokeStyle='#000';ctx.fillStyle=settings.color;expandedTemplate(settings.text).split('\n').forEach((line,i)=>{const y=Number(settings.y)+i*settings.fontSize*1.15;if(settings.outline)ctx.strokeText(line,settings.x,y);ctx.fillText(line,settings.x,y);});ctx.restore();}
function templateDialog(){
  if(!tx.source){dialog('Template editor','<div class="dialog-body"><p>Open a TX picture first.</p></div>');return;}
  dialog('Template editor',`<div class="dialog-body template-editor"><canvas id="template-preview" class="template-preview"></canvas><p>Text supports %CALL%, %TO%, %OP%, %RSV%, %X%, %Y%, %Z%, %DATE%, %TIME%, %QTH% and %LOCATOR%.</p><textarea id="template-text" rows="3" style="width:100%">${escapeHtml(templateSettings.text)}</textarea><div class="template-fields">${[['fontSize','Size','number'],['color','Text color','color'],['x','X','number'],['y','Y','number'],['background','Background','color'],['backgroundAlpha','Opacity','number']].map(([key,label,type])=>`<div class="form-row"><label>${label}</label><input id="template-${key}" type="${type}" value="${escapeHtml(templateSettings[key])}" ${key==='backgroundAlpha'?'min="0" max="1" step="0.1"':''}></div>`).join('')}</div><label><input id="template-outline" type="checkbox" ${templateSettings.outline?'checked':''}>Black text outline</label></div>`,'<button data-action="template-import">Load template…</button><button id="template-save">Save template…</button><button id="template-apply">Apply</button><button data-dialog="close">Cancel</button>');
  let staged={...templateSettings};const preview=()=>{for(const key of ['text','fontSize','color','x','y','background','backgroundAlpha'])staged[key]=['fontSize','x','y','backgroundAlpha'].includes(key)?Number($('template-'+key).value):$('template-'+key).value;staged.fontSize=Math.max(6,Math.min(200,staged.fontSize||28));staged.outline=$('template-outline').checked;const canvas=$('template-preview');canvas.width=$('tx-picture').width;canvas.height=$('tx-picture').height;paintTxPicture(canvas);applyTemplate(canvas,staged);};document.querySelectorAll('#dialog-content input,#dialog-content textarea').forEach(element=>element.oninput=preview);preview();
  $('template-apply').onclick=()=>{templateSettings=staged;persist('template',templateSettings);state.settings.useTemplate=true;persist('settings',state.settings);drawTxImage();$('modal').close();};$('template-save').onclick=()=>{const list=saved('templates',[]),created=new Date().toISOString();list.push({id:crypto.randomUUID(),name:'Template '+(list.length+1),created,url:$('template-preview').toDataURL(),settings:staged});persist('templates',list);download(new Blob([JSON.stringify(staged,null,2)],{type:'application/json'}),'sstv-template.json');status('Template saved.');};
}
async function cameraDialog(){
  dialog('Camera snapshot','<div class="dialog-body"><video id="camera-preview" autoplay playsinline muted style="width:480px;max-width:100%"></video><p id="camera-message">Opening camera…</p></div>','<button id="camera-capture" disabled>Capture</button><button data-dialog="close">Cancel</button>');
  let stream;const cleanup=()=>{stream?.getTracks().forEach(track=>track.stop());};$('modal').addEventListener('close',cleanup,{once:true});
  try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera capture requires HTTPS or localhost.');stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});if(!$('camera-preview')){cleanup();return;}$('camera-preview').srcObject=stream;await $('camera-preview').play();$('camera-message').textContent='Capture a frame to the shared TX picture.';$('camera-capture').disabled=false;$('camera-capture').onclick=()=>{const video=$('camera-preview'),canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);cleanup();$('modal').close();setTxImage(canvas,'Camera snapshot').then(()=>{if(state.settings.interface==='qsstv')qTab('transmit');}).catch(failure);};}catch(error){cleanup();if($('camera-message'))$('camera-message').textContent=error.message;}
}
const morse={A:'.-',B:'-...',C:'-.-.',D:'-..',E:'.',F:'..-.',G:'--.',H:'....',I:'..',J:'.---',K:'-.-',L:'.-..',M:'--',N:'-.',O:'---',P:'.--.',Q:'--.-',R:'.-.',S:'...',T:'-',U:'..-',V:'...-',W:'.--',X:'-..-',Y:'-.--',Z:'--..','0':'-----','1':'.----','2':'..---','3':'...--','4':'....-','5':'.....','6':'-....','7':'--...','8':'---..','9':'----.','/':'-..-.','?':'..--..','-':'-....-', '.':'.-.-.-'};
function toneWav(kind,text,seconds,frequency,endFrequency,wpm){
  const rate=12000,parts=[];let phase=0;
  const tone=(time,f1,f2=f1)=>{const n=Math.round(time*rate),samples=new Int16Array(n);for(let i=0;i<n;i++){phase+=2*Math.PI*(f1+(f2-f1)*i/Math.max(1,n-1))/rate;const edge=Math.min(1,i/60,(n-i)/60);samples[i]=f1?Math.round(Math.sin(phase)*16000*edge):0;}parts.push(samples);};
  if(kind==='cw'){const unit=1.2/wpm,words=text.trim().toUpperCase().split(/\s+/);words.forEach((word,wi)=>{if(wi)tone(unit*4,0);[...word].forEach((letter,li)=>{if(li)tone(unit*2,0);for(const symbol of morse[letter]||''){tone(unit*(symbol==='-'?3:1),frequency);tone(unit,0);}});});}
  else if(kind==='waterfall'){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=24;const ctx=canvas.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,128,24);ctx.fillStyle='#fff';ctx.font='bold 18px monospace';ctx.fillText(text.toUpperCase().slice(0,12),1,18);const pixels=ctx.getImageData(0,0,128,24).data,frames=24,frame=Math.ceil(seconds*rate/frames),samples=new Int16Array(frame*frames);for(let y=0;y<frames;y++){const carriers=[];for(let x=0;x<128;x++)if(pixels[((23-y)*128+x)*4]>80)carriers.push(700+x/127*2000);for(let n=0;n<frame;n++){const t=(y*frame+n)/rate;let v=0;for(const hz of carriers)v+=Math.sin(2*Math.PI*hz*t);samples[y*frame+n]=Math.round(v*18000/Math.max(1,carriers.length));}}parts.push(samples);}
  else tone(seconds,frequency,kind==='sweep'?endFrequency:frequency);
  return MMSAudio.wav(parts,rate);
}
function tonesDialog(kind='tone'){
  dialog('Generate audio',`<div class="dialog-body"><div class="form-row"><label>Type</label><select id="tone-type"><option value="tone">Tone</option><option value="sweep">Sweep</option><option value="cw">CW ID</option><option value="waterfall">Waterfall text / ID</option></select></div><div class="form-row"><label>Text / callsign</label><input id="tone-text" value="${escapeHtml(state.settings.myCall)}" maxlength="80"></div><div class="form-row"><label>Duration (seconds)</label><input id="tone-duration" type="number" min="0.1" max="120" value="5"></div><div class="form-row"><label>Frequency (Hz)</label><input id="tone-frequency" type="number" min="300" max="5000" value="${state.settings.cwFrequency||1500}"></div><div class="form-row"><label>Sweep end (Hz)</label><input id="tone-end" type="number" min="300" max="5000" value="2300"></div><div class="form-row"><label>CW WPM</label><input id="tone-wpm" type="number" min="5" max="60" value="${state.settings.cwWpm||15}"></div></div>`,'<button id="tone-generate">Save WAV</button><button data-dialog="close">Cancel</button>');$('tone-type').value=kind;$('tone-generate').onclick=()=>{const kind=$('tone-type').value,seconds=Math.max(.1,Math.min(120,Number($('tone-duration').value)||5)),frequency=Math.max(300,Math.min(5000,Number($('tone-frequency').value)||1500)),end=Math.max(300,Math.min(5000,Number($('tone-end').value)||2300)),wpm=Math.max(5,Math.min(60,Number($('tone-wpm').value)||15));download(toneWav(kind,$('tone-text').value,seconds,frequency,end,wpm),kind+'_'+timestamp()+'.wav');$('modal').close();};
}
function recordInput(values,rate){const input=state.input;if(!state.settings.recordAudio||input?.kind!=='mic'||input.recordDone)return;input.recordChunks||=[];input.recordBytes||=0;const pcm=Int16Array.from(values,v=>Math.round(Math.max(-1,Math.min(1,v))*32767));if(input.recordBytes+pcm.byteLength>Math.max(1,Math.min(256,state.settings.recordLimit))*1024*1024){input.recordDone=true;status('Recording limit reached; microphone reception continues.');return;}input.recordChunks.push(pcm);input.recordBytes+=pcm.byteLength;input.recordRate=rate;}
function finishRecording(input){if(input?.recordChunks?.length){download(MMSAudio.wav(input.recordChunks,input.recordRate),'microphone_'+timestamp()+'.wav');input.recordChunks=[];}}
for(const id of ['digital-file','bsr-file','history-file']){const input=document.createElement('input');input.type='file';input.id=id;input.hidden=true;if(id==='history-file')input.accept='.json';document.body.append(input);}
$('digital-file').onchange=async()=>{try{const file=$('digital-file').files[0];if(!file)return;if(file.size<1||file.size>16*1024*1024)throw Error('Digital files must be between 1 byte and 16 MB.');digital.source={name:file.name,bytes:new Uint8Array(await file.arrayBuffer())};setProtocol('drm');selectTab('tx');if(state.settings.interface==='qsstv')qTab('transmit');status('Digital file ready: '+file.name);}catch(error){failure(error);}finally{$('digital-file').value='';}};
$('history-file').onchange=async()=>{try{const file=$('history-file').files[0];if(!file)return;if(file.size>64*1024*1024)throw Error('History backup exceeds 64 MB.');const data=JSON.parse(await file.text());if(data.format!=='MMSSTV-web-history'||!Array.isArray(data.pictures))throw Error('Invalid history backup.');for(const row of data.pictures.slice(-state.settings.historyLimit)){if(typeof row.url!=='string'||!/^data:image\/(png|jpeg|bmp);base64,/.test(row.url)||row.url.length>16*1024*1024)continue;const image=new Image();image.src=row.url;await image.decode();if(image.width*image.height>40000000)continue;const item={id:crypto.randomUUID(),kind:'history',created:new Date(row.created||Date.now()).toISOString(),mode:String(row.mode||'SSTV').slice(0,80),call:String(row.call||'').slice(0,30),width:image.width,height:image.height,url:row.url};state.history.push(item);await storeImage(item);}while(state.history.length>state.settings.historyLimit)await storeImage(state.history.shift(),true);renderStock();drawHistory();status('History imported.');}catch(error){failure(error);}finally{$('history-file').value='';}};
Object.assign(actions,{'digital-open':()=>$('digital-file').click(),'digital-files':digitalFilesDialog,'digital-bsr':bsrDialog,'digital-fix':fixDialog,'digital-generate':digitalGenerateDialog,'import-history':()=>$('history-file').click(),'q-configuration':qConfiguration,template:templateDialog,'template-refresh':()=>drawTxImage(),camera:cameraDialog,tones:()=>tonesDialog(),'cw-id':()=>tonesDialog('cw'),'waterfall-text':()=>tonesDialog('waterfall'),'waterfall-id':()=>tonesDialog('waterfall'),'protocol-drm':()=>setProtocol('drm'),'protocol-sstv':()=>setProtocol('sstv'),'generate-wav':()=>digital.protocol==='drm'?digitalGenerateDialog():generateWavDialog()});
// Add the shared features to MMSSTV menus without changing its workspace layout.
const fileMenu=$('desktop').querySelector('.menu-popup');for(const [action,label]of [['digital-open','Open DRM file…'],['digital-generate','Generate DRM WAV…'],['digital-files','Received digital files…'],['digital-bsr','Block status request…'],['digital-fix','FIX / retransmit…'],['import-history','Import history…']]){const button=document.createElement('button');button.dataset.action=action;button.textContent=label;fileMenu.append(button);}
const optionMenu=$('desktop').querySelector('[data-action="settings"]').parentElement;for(const [action,label]of [['q-configuration','Shared configuration…'],['tones','Generate tone / sweep / CW…']]){const button=document.createElement('button');button.dataset.action=action;button.textContent=label;optionMenu.append(button);}
for(const button of $('desktop').querySelectorAll('button'))if(button.textContent==='Template'||button.textContent==='Edit template'){button.disabled=false;button.dataset.action='template';button.title='Edit the shared TX template';}
const protocolBar=document.createElement('div');protocolBar.className='tabs';protocolBar.innerHTML='<button data-action="protocol-sstv">SSTV</button><button data-action="protocol-drm">DRM</button>';protocolBar.setAttribute('aria-label','Receive protocol');$('desktop').querySelector('.stock-tabs').before(protocolBar);
window.addEventListener('beforeunload',event=>{if(state.settings.confirmClose){event.preventDefault();event.returnValue='';}});

const originalDeleteHistory=actions['delete-history'];
actions['delete-history']=()=>{if(!state.settings.confirmDelete)return originalDeleteHistory();dialog('Delete picture','<div class="dialog-body"><p>Delete this picture from shared history?</p></div>','<button id="confirm-delete">Delete</button><button data-dialog="close">Cancel</button>');$('confirm-delete').onclick=()=>{originalDeleteHistory();$('modal').close();};};
actions['print-image']=()=>{const url=currentCanvas().toDataURL('image/png');dialog('Print picture',`<div class="dialog-body"><img class="print-picture" src="${url}" alt="Current picture" style="max-width:100%"></div>`,'<button id="print-now">Print</button><button data-dialog="close">Close</button>');$('print-now').onclick=()=>window.print();};
actions['find-log']=()=>{dialog('Find QSO','<div class="dialog-body"><input id="log-query" placeholder="Callsign, name, QTH or note"><div id="log-results" class="dialog-scroll"></div></div>');const find=()=>{$('log-results').innerHTML=state.logs.filter(r=>[r.call,r.name,r.qth,r.note].some(v=>String(v).toLowerCase().includes($('log-query').value.toLowerCase()))).map(r=>`<p><b>${escapeHtml(r.call)}</b> ${escapeHtml(r.time)} · ${escapeHtml(r.mode)}<br>${escapeHtml(r.name)} ${escapeHtml(r.qth)} ${escapeHtml(r.note)}</p>`).join('')||'<p>No matching entries.</p>';};$('log-query').oninput=find;find();};
const mmsDrm=document.createElement('div');mmsDrm.id='mms-drm-state';mmsDrm.hidden=true;protocolBar.after(mmsDrm);
const originalNotifyView=notifyView;
notifyView=()=>{mmsDrm.hidden=digital.protocol!=='drm';if(!mmsDrm.hidden){const d=digital.snapshot,s=d?.status||[];mmsDrm.innerHTML=`<b>DRM ${['A','B','E','D'][s[4]]||''}</b> ${escapeHtml(d?.call||'')} · ${Number(d?.snr||0).toFixed(1)} dB<br>TIME ${s[0]?'✓':'—'} FRAME ${s[1]?'✓':'—'} FAC ${s[2]?'✓':'—'} MSC ${s[3]?'✓':'—'}<br>Segments ${s[11]||0}/${s[12]||0}<br>${escapeHtml(digital.files.at(-1)?.name||'')}<br><button data-action="digital-files">Files…</button> <button data-action="digital-bsr">BSR…</button>`;}originalNotifyView();};
$('mms-template').checked=!!state.settings.useTemplate;$('mms-template').onchange=()=>{state.settings.useTemplate=$('mms-template').checked;persist('settings',state.settings);drawTxImage();};
const templateInput=document.createElement('input');templateInput.type='file';templateInput.accept='.json';templateInput.hidden=true;templateInput.id='template-file';document.body.append(templateInput);templateInput.onchange=async()=>{try{const file=templateInput.files[0];if(!file)return;if(file.size>65536)throw Error('Template file exceeds 64 KB.');const input=JSON.parse(await file.text());if(typeof input.text!=='string'||input.text.length>4096)throw Error('Invalid template.');const s={...templateSettings};for(const key of ['text','color','background','backgroundAlpha','fontSize','x','y','outline'])if(key in input)s[key]=input[key];s.fontSize=Math.max(6,Math.min(200,Number(s.fontSize)||28));templateSettings=s;templateDialog();}catch(error){failure(error);}finally{templateInput.value='';}};
actions['template-import']=()=>templateInput.click();

async function finishGeneratedAudio(chunks,rate){
 const pcm=async blob=>{const audio=MMSAudio.readWav(await blob.arrayBuffer()),samples=new MMSAudio.Resampler(audio.rate,rate).push(audio.samples,true);return Int16Array.from(samples,x=>Math.round(Math.max(-1,Math.min(1,x))*32767));};
 const parts=[];if(state.settings.txVox)parts.push(await pcm(toneWav('tone','',1,1700,1700,15)));parts.push(...chunks);if(state.settings.txCw&&state.settings.myCall)parts.push(await pcm(toneWav('cw',state.settings.myCall,1,state.settings.cwFrequency,state.settings.cwFrequency,state.settings.cwWpm)));return MMSAudio.wav(parts,rate);
}

for(const button of $('desktop').querySelectorAll('.stock-tabs > button')){if(button.textContent==='S.pix'){button.onclick=()=>{state.stockKind='pictures';state.stockPage=0;renderStock();};}else if(button.textContent.startsWith('S.templates')||/^[234]$/.test(button.textContent)){button.disabled=false;button.title='Shared TX templates';button.onclick=()=>{state.stockKind='templates';state.stockPage=/^[234]$/.test(button.textContent)?Number(button.textContent)-1:0;renderStock();};}}
