/* Alternate QSSTV layout over the shared application session. */
'use strict';
const qsstv=document.createElement('main');qsstv.id='qsstv';qsstv.className='desktop qsstv';qsstv.hidden=true;qsstv.setAttribute('aria-label','QSSTV browser application');
const qbutton=(action,label,icon)=>`<button data-action="${action}" title="${label}" ${icon?'class="q-icon"':''}>${icon?`<img src="assets/${icon}.png" alt="${label}">`:label}</button>`;
qsstv.innerHTML=`<div class="titlebar"><img src="assets/qsstv/qsstv.png" alt=""><span>QSSTV — 9.5.11 (Web)</span><a href="#mmsstv" id="switch-mmsstv" class="interface-switch">Switch to MMSSTV</a></div>
<nav class="menubar" aria-label="QSSTV menu"><div class="menu"><button aria-expanded="false">File</button><div class="menu-popup">${qbutton('open-audio','Open audio…')}${qbutton('microphone','Audio input from microphone…')}${qbutton('tx-open','Open TX image…')}${qbutton('digital-open','Open DRM file…')}${qbutton('save-image','Save image…')}${qbutton('digital-files','Received digital files…')}${qbutton('import-history','Import history…')}${qbutton('export-history','Export history…')}${qbutton('export-log','Export log…')}${qbutton('log-list','QSO log…')}${qbutton('print-image','Print picture…')}</div></div><div class="menu"><button aria-expanded="false">Options</button><div class="menu-popup">${qbutton('q-configuration','Configuration…')}${qbutton('settings','SSTV receiver setup…')}${qbutton('template','Template editor…')}${qbutton('tones','Tone / sweep / CW / waterfall text…')}<button disabled>CAT / rig control</button><button disabled>PTT</button><button disabled>FTP / hybrid server</button></div></div><div class="menu"><button aria-expanded="false">Help</button><div class="menu-popup">${qbutton('q-about','About QSSTV…')}${qbutton('help','Help…')}</div></div></nav>
<div class="tabs q-tabs" role="tablist" aria-label="QSSTV views"><button data-qtab="receive" role="tab" aria-selected="true">Receive</button><button data-qtab="transmit" role="tab" aria-selected="false">Transmit</button><button data-qtab="gallery" role="tab" aria-selected="false">Gallery</button></div>
<div class="q-workspace"><section class="q-picture-column"><div class="q-tools" id="q-tools-rx">${qbutton('microphone','Start microphone','qsstv/start')}${qbutton('stop','Stop input','qsstv/stop')}${qbutton('resync','Restart reception','qsstv/replay')}${qbutton('save-image','Save picture','qsstv/filesave')}${qbutton('clear-image','Erase picture','qsstv/eraser')}${qbutton('open-audio','Open audio','SBFolder')}</div><div class="q-tools" id="q-tools-tx" hidden>${qbutton('q-generate','Generate WAV','qsstv/start')}${qbutton('q-cancel','Cancel generation','qsstv/stop')}${qbutton('tx-open','Open picture','SBFolder')}${qbutton('image-editor','Edit TX picture','SBAdj')}${qbutton('template','Edit template','SBText')}${qbutton('camera','Camera snapshot','qsstv/camera')}${qbutton('digital-open','Open binary file','qsstv/binary')}${qbutton('tones','Generate tones','qsstv/tone')}</div><div class="q-picture-well" id="q-picture-well"><canvas id="q-picture" width="320" height="256" aria-label="QSSTV current image"></canvas><div id="q-picture-label"></div></div><div class="tabs" id="q-gallery-tabs" hidden><button data-gallery="rx" class="selected">RX SSTV</button><button data-gallery="drm">RX DRM</button><button data-gallery="stock">TX Stock</button><button data-gallery="templates">Templates</button></div><div id="q-gallery" class="q-gallery" hidden></div><div id="q-gallery-pager" hidden>${qbutton('q-first','⏮')}${qbutton('q-prev','◀')}<span id="q-page">Page 1 of 1</span>${qbutton('q-next','▶')}${qbutton('q-last','⏭')}</div><div id="q-tx-size" hidden>Size <span></span><input id="q-image-size" type="range" min="128" max="1600" step="32" value="640" aria-label="Digital image maximum dimension"><button data-action="q-generate">Generate WAV…</button></div></section>
<div class="q-meters"><div class="q-meter"><i id="q-sync-level"></i><span>S</span></div><div class="q-meter"><i id="q-volume-level"></i><span>V</span></div></div>
<section class="q-controls" id="q-controls"><div class="tabs q-protocol" role="tablist" aria-label="Transmission protocol"><button data-protocol="sstv" role="tab" aria-selected="true">SSTV</button><button data-protocol="drm" role="tab" aria-selected="false">DRM</button></div><div id="q-sstv-rx"><label>Auto Slant <input id="q-slant" type="checkbox"></label><label>Autosave <input id="q-autosave" type="checkbox"></label><label>Sensitivity <select id="q-sensitivity"><option value="0">Low</option><option value="1">High</option><option value="2">DX</option><option value="3">Highest</option></select></label><label>Mode <select id="q-rx-mode"></select></label><button data-action="wefax-settings" id="q-fax-rx" hidden>WEFAX settings…</button><label>Default Image format <select id="q-format"><option value="png">png</option><option value="jpeg">jpg</option><option value="bmp">bmp</option></select></label><label>Save if Complete (%) <input id="q-percent" type="number" min="0" max="100"></label><label class="q-call-label">Call: <input id="q-call" maxlength="30"><button id="q-log">LOG QSO</button></label><div class="q-rx-state" id="q-rx-state">No sync</div></div>
<div id="q-drm-rx" hidden><div class="q-drm-info" id="q-drm-info"></div><div class="q-indicators"><span>TIME</span><span>FRAME</span><span>FAC</span><span>MSC</span></div><progress id="q-segments" value="0" max="1"></progress><div id="q-drm-file"></div><button data-action="digital-files">Received files…</button><button data-action="digital-bsr">BSR…</button><div class="q-constellations"><label>FAC<canvas id="q-fac" width="118" height="90"></canvas></label><label>MSC<canvas id="q-msc" width="118" height="90"></canvas></label></div><div class="q-drm-log" id="q-drm-log"></div></div>
<div id="q-tx-settings" hidden><div id="q-sstv-tx"><label>Mode <select id="q-tx-mode"></select></label><button data-action="wefax-settings" id="q-fax-tx" hidden>WEFAX settings…</button><label>Resize <select id="q-fit"><option value="stretch">Stretch</option><option value="fit">Fit</option><option value="crop">Crop</option></select></label><label>FSK ID <input id="q-fsk" type="checkbox"></label></div><fieldset id="q-drm-tx" hidden><div id="q-drm-fields"></div><label>RS <select id="q-rs"><option value="0">None</option><option value="1">RS1 (224)</option><option value="2">RS2 (192)</option><option value="3">RS3 (160)</option><option value="4">RS4 (128)</option></select></label><button data-action="digital-fix">FIX / retransmit…</button></fieldset><label>VOX lead-in <input id="q-vox" type="checkbox"></label><label>CW ID <input id="q-cw" type="checkbox"></label><label>My call <input id="q-mycall" maxlength="18"></label><label>Use Template <input id="q-template" type="checkbox"></label><label>To: <input id="q-to"></label><label>Op: <input id="q-op"></label><label>RSV <input id="q-rsv" value="595"></label><label>x <input id="q-x"></label><label>y <input id="q-y"></label><label>z <input id="q-z"></label><button data-action="template-refresh" class="q-refresh">Refresh</button><div id="q-tx-file"></div></div></section>
<aside class="q-scope"><canvas id="q-spectrum" width="170" height="100" aria-label="QSSTV audio spectrum"></canvas><canvas id="q-waterfall" width="170" height="360" aria-label="QSSTV waterfall"></canvas><div class="q-scope-settings"><label>Max dB<input id="q-max-db" type="number" value="-25" min="-80" max="0"></label><label>Range<input id="q-range" type="number" value="35" min="10" max="80"></label><label>Avg<input id="q-average" type="number" value="0.9" min="0" max="0.99" step="0.01"></label></div></aside></div>
<div class="q-bottom"><span class="q-no-rig">No Rig</span><input id="q-frequency" value="14.230" aria-label="Log frequency MHz"><button data-action="waterfall-text">WF Text</button><button data-action="digital-bsr">BSR</button><button data-action="waterfall-id">WF ID</button><button data-action="cw-id">CW ID</button><button disabled title="Hardware control is unavailable">PTT</button><span class="q-ptt" title="Hardware output disabled"></span></div><div class="audio-bar"><button data-action="microphone">Mic…</button><button data-action="open-audio">Open audio…</button><button id="q-pause" data-action="pause">Pause</button><button data-action="stop">Stop</button><div class="source-summary"><span id="q-source">No audio input</span><progress id="q-progress" max="1" value="0"></progress></div></div><div class="statusbar"><span id="q-status">Ready</span><span id="q-time">00:00</span></div>`;
document.body.insertBefore(qsstv,$('desktop').nextSibling);
const view={name:state.settings.interface==='qsstv'?'qsstv':'mmsstv',tab:'receive',gallery:'rx',page:0,lastRevision:-1,lastDigital:-1,lastGallery:'',modeCount:0,averages:new Float32Array(170)};
const drmFields=[['mode','Mode',['A','B','E']],['qam','QAM',['4','16','64']],['protection','Prot.',['High','Normal']],['bandwidth','BW',['2.2 kHz','2.5 kHz']],['interleave','Interleave',['Long','Short']]];
$('q-drm-fields').innerHTML=drmFields.map(([key,label,choices])=>`<label>${label}<select id="q-drm-${key}">${choices.map((text,i)=>`<option value="${i}">${text}</option>`).join('')}</select></label>`).join('');
function switchInterface(name){view.name=name;state.settings.interface=name;persist('settings',state.settings);$('desktop').hidden=name!=='mmsstv';qsstv.hidden=name!=='qsstv';document.title=name==='qsstv'?'QSSTV Web':'MMSSTV Web';if(name==='qsstv')view.tab=state.tab==='tx'?'transmit':state.tab==='history'?'gallery':'receive';view.lastRevision=-1;refreshQSSTV();}
function qTab(tab){view.tab=tab;if(tab==='transmit')selectTab('tx');else if(tab==='receive')selectTab('rx');else selectTab('history');view.lastRevision=-1;refreshQSSTV();}
function qGalleryEntries(){return view.gallery==='stock'?state.stocks:view.gallery==='templates'?saved('templates',[]):state.history.filter(item=>view.gallery==='drm'?item.mode==='DRM':item.mode!=='DRM');}
function renderQGallery(){
 const entries=qGalleryEntries(),rows=Math.max(1,Math.min(8,state.settings.galleryRows)),columns=Math.max(1,Math.min(8,state.settings.galleryColumns)),count=rows*columns,pages=Math.max(1,Math.ceil(entries.length/count));view.page=Math.max(0,Math.min(pages-1,view.page));
 const key=entries.map(i=>i.id).join(',')+view.page+rows+columns+view.gallery;if(key===view.lastGallery)return;view.lastGallery=key;
 $('q-gallery').style.gridTemplateColumns=`repeat(${columns},minmax(0,1fr))`;$('q-gallery').style.gridTemplateRows=`repeat(${rows},minmax(0,1fr))`;$('q-gallery').replaceChildren();
 for(let i=0;i<count;i++){const item=entries[view.page*count+i],button=document.createElement('button');button.className='q-gallery-cell';if(item){const image=document.createElement('img');image.src=item.url;image.alt=item.name||item.mode||'Template';button.append(image);button.title=(item.name||item.mode)+' '+(item.created||'');button.onclick=()=>{if(view.gallery==='stock')setTxImage(item.url,item.name).then(()=>qTab('transmit')).catch(failure);else if(view.gallery==='templates'){templateSettings=item.settings||templateSettings;templateDialog();}else{state.historyIndex=state.history.findIndex(r=>r.id===item.id);drawHistory();zoomImage(item.url,item.mode);}};}else button.disabled=true;$('q-gallery').append(button);}
 $('q-page').textContent=`Page ${view.page+1} of ${pages}`;
}
function qSignal(){
 const snap=state.snapshot;if(!snap)return;
 const spectrum=$('q-spectrum'),ctx=spectrum.getContext('2d'),w=spectrum.width,h=spectrum.height,max=Number($('q-max-db').value),range=Number($('q-range').value),avg=Number($('q-average').value);
 ctx.fillStyle='#000080';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#00ff00';ctx.beginPath();const row=new Uint8ClampedArray(w*4);
 for(let x=0;x<w;x++){const bin=Math.round((700+x/w*2000)*2048/11025),power=snap.spectrum[bin]||0,gain=[30,34,42,54][state.settings.fftGain&3],scale=[-5.5,-6.5,-7.8,-9][state.settings.fftGain&3],db=10*(power/gain-scale)-144.49;const level=Math.max(0,Math.min(1,(db-max+range)/range));view.averages[x]=view.averages[x]*avg+level*(1-avg);const y=h-1-view.averages[x]*(h-2);x?ctx.lineTo(x,y):ctx.moveTo(x,y);const i=x*4;row[i]=Math.max(0,(level-.75)*700);row[i+1]=Math.min(255,level*430);row[i+2]=Math.min(255,level*650);row[i+3]=255;}
 ctx.stroke();for(const f of [1200,1500,1900,2300]){ctx.strokeStyle='#f00';ctx.beginPath();const x=(f-700)/2000*w;ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}
 const wf=$('q-waterfall'),wc=wf.getContext('2d');wc.drawImage(wf,0,1);wc.putImageData(new ImageData(row,w,1),0,0);
 $('q-volume-level').style.height=Math.min(100,Math.max(0,snap.level*200))+'%';$('q-sync-level').style.height=(digital.protocol==='drm'?(digital.snapshot?.status[0]?100:0):snap.receiving?100:0)+'%';
}
function refreshQSSTV(){
 if(view.name!=='qsstv')return;view.tab=state.tab==='tx'?'transmit':state.tab==='history'?'gallery':'receive';
 if(view.modeCount!==state.modes.length&&state.modes.length){view.modeCount=state.modes.length;$('q-rx-mode').replaceChildren(new Option('Auto',-1));$('q-tx-mode').replaceChildren();for(const m of state.modes){$('q-rx-mode').add(new Option(m.name,m.id));$('q-tx-mode').add(new Option(m.name,m.id));}}
 const gallery=view.tab==='gallery',transmit=view.tab==='transmit',drm=digital.protocol==='drm';
 document.querySelectorAll('[data-qtab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.qtab===view.tab)));document.querySelectorAll('[data-protocol]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.protocol===digital.protocol)));
 $('q-tools-rx').hidden=gallery||transmit;$('q-tools-tx').hidden=gallery||!transmit;$('q-picture-well').hidden=gallery;for(const id of ['q-gallery','q-gallery-tabs','q-gallery-pager'])$(id).hidden=!gallery;$('q-controls').hidden=gallery;$('q-tx-size').hidden=!transmit;
 $('q-sstv-rx').hidden=transmit||drm;$('q-drm-rx').hidden=transmit||!drm;$('q-tx-settings').hidden=!transmit;$('q-sstv-tx').hidden=drm;$('q-drm-tx').hidden=!drm;qsstv.classList.toggle('q-gallery-view',gallery);
 $('q-slant').checked=state.settings.autoSlant;$('q-autosave').checked=state.settings.autoHistory;$('q-sensitivity').value=state.settings.sensitivity;$('q-format').value=state.settings.imageFormat;
 if(document.activeElement!==$('q-percent'))$('q-percent').value=state.settings.savePercent;
 $('q-fax-rx').hidden=drm||!isWEFAXMode(state.mode);$('q-fax-tx').hidden=drm||!isWEFAXMode(tx.mode);$('q-fsk').disabled=isWEFAXMode(tx.mode);$('q-rx-mode').value=state.mode;$('q-tx-mode').value=tx.mode;$('q-fit').value=tx.fit;$('q-fsk').checked=state.settings.txFskId;$('q-vox').checked=!!state.settings.txVox;$('q-cw').checked=!!state.settings.txCw;$('q-image-size').hidden=!drm;$('q-image-size').value=state.settings.digitalImageSize||640;$('q-template').checked=!!state.settings.useTemplate;$('mms-template').checked=!!state.settings.useTemplate;qsstv.classList.toggle('q-low-resolution',!!state.settings.lowResolution);
 if(document.activeElement!==$('q-call'))$('q-call').value=$('call').value;if(document.activeElement!==$('q-mycall'))$('q-mycall').value=state.settings.myCall;if(document.activeElement!==$('q-frequency'))$('q-frequency').value=$('frequency').value;
 $('q-rx-state').textContent=isWEFAXMode(state.snapshot?.mode)?$('rx-info').textContent:state.snapshot?.receiving?'Receiving '+(state.modes[state.snapshot.mode]?.name||'SSTV'):'No sync';
 const source=transmit?$('tx-picture'):$('rx-picture'),canvas=$('q-picture');canvas.width=source.width;canvas.height=source.height;if(transmit?!!tx.source:state.hasImage)canvas.getContext('2d').drawImage(source,0,0);else clearCanvas(canvas,state.settings.imageBackground);canvas.style.objectFit=state.settings.stretch?'fill':'contain';$('q-picture-well').style.background=state.settings.imageBackground;$('q-picture-label').textContent=transmit?tx.name:'';
 $('q-tx-size').querySelector('span').textContent=`${source.width} × ${source.height}`;$('q-tx-file').textContent=digital.source?.name||'';
 for(const [key]of drmFields)$('q-drm-'+key).value=digital.settings[key];$('q-rs').value=digital.settings.rs;for(const b of qsstv.querySelectorAll('[data-action=stop]'))b.disabled=!state.input;
 for(const b of qsstv.querySelectorAll('[data-action=digital-bsr]'))b.disabled=!drm;
 const ds=digital.snapshot,s=ds?.status||[];$('q-drm-info').innerHTML=[['Mode',['A','B','E','D'][s[4]]||'—'],['QAM',s[5]===3?4:s[5]===1?16:64],['BW',s[6]?'2.5 kHz':'2.2 kHz'],['Interl.',s[7]?'Short':'Long'],['Protect.',s[8]?'Normal':'High'],['SNR',Number(ds?.snr||0).toFixed(1)+' dB'],['Offset',Number(ds?.offset||0).toFixed(1)+' Hz'],['Transp. ID',s[9]||0],['Cur. Seg',s[10]||0],['RX Seg',s[11]||0],['Total Seg',s[12]||0],['Callsign',ds?.call||'']].map(([key,value])=>`<label>${key}<output>${escapeHtml(value)}</output></label>`).join('');
 document.querySelectorAll('.q-indicators span').forEach((element,i)=>element.classList.toggle('valid',!!s[i]));$('q-segments').max=s[12]||1;$('q-segments').value=s[11]||0;$('q-drm-file').textContent=digital.files.at(-1)?.name||'';$('q-drm-log').textContent=digital.files.slice(-12).map(file=>file.name+' · '+file.bytes.length+' bytes').join('\n');
 if(ds?.constellations)for(let kind=0;kind<2;kind++){const c=$(kind?'q-msc':'q-fac'),ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#000080';ctx.beginPath();ctx.moveTo(c.width/2,0);ctx.lineTo(c.width/2,c.height);ctx.moveTo(0,c.height/2);ctx.lineTo(c.width,c.height/2);ctx.stroke();ctx.fillStyle='#0000c0';const points=ds.constellations[kind];for(let i=0;i<points.length;i+=2)ctx.fillRect(c.width/2+points[i]*c.width/3,c.height/2-points[i+1]*c.height/3,2,2);}
 $('q-status').textContent=$('status').textContent;$('q-time').textContent=$('time-status').textContent;$('q-source').textContent=$('source-name').textContent;$('q-progress').value=$('file-progress').value;$('q-pause').textContent=state.paused?'Resume':'Pause';$('q-pause').disabled=state.input?.kind!=='file';for(const b of $('q-tools-rx').querySelectorAll('button'))if(b.dataset.action==='stop')b.disabled=!state.input;else if(['save-image','clear-image'].includes(b.dataset.action))b.disabled=!state.hasImage;for(const b of $('q-tools-tx').querySelectorAll('button'))if(b.dataset.action==='q-generate')b.disabled=tx.busy||!(tx.source||digital.source&&drm);else if(b.dataset.action==='q-cancel')b.disabled=!tx.busy;$('q-tx-size').querySelector('button').disabled=tx.busy||!(tx.source||digital.source&&drm);
 if(gallery)renderQGallery();if(state.snapshot&&view.lastRevision!==lastVisual){view.lastRevision=lastVisual;qSignal();}
}
window.QSSTVUI={refresh:refreshQSSTV};
$('switch-qsstv').onclick=e=>{e.preventDefault();switchInterface('qsstv');};$('switch-mmsstv').onclick=e=>{e.preventDefault();switchInterface('mmsstv');};
qsstv.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.qtab)qTab(b.dataset.qtab);if(b.dataset.protocol)setProtocol(b.dataset.protocol);if(b.dataset.gallery){view.gallery=b.dataset.gallery;view.page=0;document.querySelectorAll('[data-gallery]').forEach(tab=>tab.classList.toggle('selected',tab===b));renderQGallery();}});
for(const [id,key]of [['q-slant','autoSlant'],['q-autosave','autoHistory'],['q-sensitivity','sensitivity'],['q-format','imageFormat'],['q-percent','savePercent'],['q-fsk','txFskId'],['q-vox','txVox'],['q-cw','txCw']])$(id).onchange=()=>{state.settings[key]=$(id).type==='checkbox'?$(id).checked:$(id).type==='number'||id==='q-sensitivity'?Number($(id).value):$(id).value;if(key==='savePercent')state.settings[key]=Math.max(0,Math.min(100,state.settings[key]||0));persist('settings',state.settings);applySettings().catch(failure);};
$('q-rx-mode').onchange=()=>resetReceiver(Number($('q-rx-mode').value)).catch(failure);$('q-tx-mode').onchange=()=>setTxMode(Number($('q-tx-mode').value));$('q-fit').onchange=()=>{tx.fit=$('q-fit').value;state.settings.txFit=tx.fit;persist('settings',state.settings);drawTxImage();};$('q-call').oninput=()=>{$('call').value=$('q-call').value;};$('q-log').onclick=()=>$('save-qso').click();$('q-frequency').oninput=()=>{$('frequency').value=$('q-frequency').value;};$('q-template').onchange=()=>{state.settings.useTemplate=$('q-template').checked;persist('settings',state.settings);drawTxImage();};$('q-mycall').onchange=()=>{state.settings.myCall=$('q-mycall').value.toUpperCase();persist('settings',state.settings);};
for(const [key]of drmFields)$('q-drm-'+key).onchange=()=>{digital.settings[key]=Number($('q-drm-'+key).value);persist('digital',digital.settings);};$('q-rs').onchange=()=>{digital.settings.rs=Number($('q-rs').value);persist('digital',digital.settings);};
Object.assign(actions,{'q-first':()=>{view.page=0;renderQGallery();},'q-prev':()=>{view.page--;renderQGallery();},'q-next':()=>{view.page++;renderQGallery();},'q-last':()=>{view.page=9999;renderQGallery();},'q-generate':()=>digital.protocol==='drm'?digitalGenerateDialog():generateWavDialog(),'q-cancel':()=>{++tx.token;},'q-configuration':qConfiguration,'q-about':()=>dialog('About QSSTV',`<div class="dialog-body"><p><b>QSSTV 9.5.11 — Web</b><br>Original program by Johan Maes, ON4QZ.<br>DRM modem by M. Bos, PA0MBO, and the Dream contributors.</p><p>SSTV and DRM use the shared browser audio, images, history and log. Transmission generates WAV files.</p><div class="link-row"><a href="licenses/QSSTV-COPYING.txt" target="_blank" rel="noopener">License</a><a href="https://github.com/crashdemons-external/mmsstv-web" target="_blank" rel="noopener">Source code</a><a href="https://github.com/ON4QZ/QSSTV" target="_blank" rel="noopener">QSSTV upstream</a></div></div>`)});
document.body.style.backgroundColor=state.settings.backgroundColor;for(const [id,key]of [['q-max-db','waterfallMax'],['q-range','waterfallRange'],['q-average','waterfallAverage']])$(id).value=state.settings[key];switchInterface(view.name);

for(const [id,key,low,high]of [['q-max-db','waterfallMax',-80,0],['q-range','waterfallRange',10,80],['q-average','waterfallAverage',0,.99]])$(id).onchange=()=>{const value=Math.max(low,Math.min(high,Number($(id).value)));$(id).value=value;state.settings[key]=value;persist('settings',state.settings);};

$('q-image-size').oninput=()=>{state.settings.digitalImageSize=Number($('q-image-size').value);persist('settings',state.settings);drawTxImage();};
